<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>gala</string>
	</array>
	<key>name</key>
	<string>Gala</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#doc-comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#numbers</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#effects</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#quantum-keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#gates</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#builtins</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operators</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#punctuation</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#identifiers</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>builtins</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(print|println|assert|len|sample|expectation|distribution|backend)\b</string>
					<key>name</key>
					<string>support.function.builtin.gala</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.gala</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#comments</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>match</key>
					<string>//.*$</string>
					<key>name</key>
					<string>comment.line.double-slash.gala</string>
				</dict>
			</array>
		</dict>
		<key>doc-comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>///.*$</string>
					<key>name</key>
					<string>comment.block.documentation.gala</string>
				</dict>
			</array>
		</dict>
		<key>effects</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(pure|quantum|prob)\b</string>
					<key>name</key>
					<string>storage.type.effect.gala</string>
				</dict>
			</array>
		</dict>
		<key>gates</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(h|x|y|z|s|t|rx|ry|rz|cx|cz|swap)\b</string>
					<key>name</key>
					<string>support.function.gate.gala</string>
				</dict>
			</array>
		</dict>
		<key>identifiers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b[A-Za-z_\u03B1-\u03C8][A-Za-z0-9_\u03B1-\u03C8]*\b</string>
					<key>name</key>
					<string>variable.other.gala</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(if|else|match|for|in|while|return|drop)\b</string>
					<key>name</key>
					<string>keyword.control.gala</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(fn|let|mut|import|from|as|type|struct|enum|trait|impl|const|where)\b</string>
					<key>name</key>
					<string>keyword.declaration.gala</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(true|false)\b</string>
					<key>name</key>
					<string>constant.language.gala</string>
				</dict>
			</array>
		</dict>
		<key>numbers</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b\d+[iIjJ]\b</string>
					<key>name</key>
					<string>constant.numeric.complex.gala</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b\d+\.\d*([eE][+-]?\d+)?\b</string>
					<key>name</key>
					<string>constant.numeric.float.gala</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b0[xX][0-9a-fA-F]+\b</string>
					<key>name</key>
					<string>constant.numeric.integer.hex.gala</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b0[bB][01]+\b</string>
					<key>name</key>
					<string>constant.numeric.integer.binary.gala</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b\d+\b</string>
					<key>name</key>
					<string>constant.numeric.integer.gala</string>
				</dict>
			</array>
		</dict>
		<key>operators</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[+\-*/%]</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.gala</string>
				</dict>
				<dict>
					<key>match</key>
					<string>==|!=|&lt;=|&gt;=|&lt;|&gt;</string>
					<key>name</key>
					<string>keyword.operator.comparison.gala</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&amp;&amp;|\|\||!</string>
					<key>name</key>
					<string>keyword.operator.logical.gala</string>
				</dict>
				<dict>
					<key>match</key>
					<string>=</string>
					<key>name</key>
					<string>keyword.operator.assignment.gala</string>
				</dict>
				<dict>
					<key>match</key>
					<string>-&gt;</string>
					<key>name</key>
					<string>keyword.operator.arrow.gala</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.\.</string>
					<key>name</key>
					<string>keyword.operator.range.gala</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\|</string>
					<key>name</key>
					<string>keyword.operator.pipe.gala</string>
				</dict>
			</array>
		</dict>
		<key>punctuation</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[{}()\[\]]</string>
					<key>name</key>
					<string>punctuation.definition.bracket.gala</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[,;:]</string>
					<key>name</key>
					<string>punctuation.delimiter.gala</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>punctuation.accessor.gala</string>
				</dict>
			</array>
		</dict>
		<key>quantum-keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(qubit|qubits|measure|reverse|adjoint|control|grad|drop)\b</string>
					<key>name</key>
					<string>keyword.quantum.gala</string>
				</dict>
			</array>
		</dict>
		<key>strings</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.gala</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.gala</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.gala</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.gala</string>
				</dict>
			</array>
		</dict>
		<key>types</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(Qubit|Qubits|Measured|Bool|Int|Float|Complex|Vec|Params|String|Unit|Self)\b</string>
					<key>name</key>
					<string>support.type.primitive.gala</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.gala</string>
</dict>
</plist>
